name: CI - Student System

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check JS syntax
        run: node -c register.js || true

      - name: Check JS syntax login
        run: node -c login.js || true

      - name: Check JS syntax search
        run: node -c search.js || true

      - name: Success
        run: echo "CI OK"